name: SIM7600 Add-on
version: "1.0.0"
slug: sim7600addon
description: SIM7600 GSM modem for Home Assistant

arch:
  - amd64

startup: services
boot: auto

init: false

host_network: true

ports:
  5000/tcp: 5000

devices:
  - /dev/serial/by-id:/dev/serial/by-id

options:
  port: "/dev/serial/by-id/CHANGE_ME"
  baudrate: 9600

schema:
  port: str
  baudrate: int
